### ISSUE TITLE
bilibiil 看av号 | 小欢wise

### ISSUE THREAD

**Issue by XiaoHuanwise** [XiaoHuanwise/XiaoHuanwise.github.io#2]
https://xiaohuanwise.github.io/post/bilibiil-kan-av-hao/ 

 F12   console    window.INITIAL_STATE.aid

**Comment by x-liuier** [comment]
# 蒟蒻前来%dalao

%19260817

**Comment by EP508** [comment]
#蒟蒻前来%dalao
%19260817
